### PR TITLE
Unlink template only if it exists

### LINKED ISSUE #503: unlink(cloud/themes/example/core/templates/lostpassword/email.php): No such file or directory at /cloud/apps/templateeditor/lib/mailtemplate.php#127
### Steps to reproduce
1. Select a mail template in admin-panel
2. select in the left menu "example" and in the right any template
3. now click on "reset" (Zurücksetzen in German)

### Expected behaviour
Tell us what should happen
the button should not displayed, because I've no template to reset (thats the default one)

### Actual behaviour
Tell us what happens instead
error message in log

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6.

**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
9.0.53 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
nothing
```
</details>

**List of activated apps:**
<details>
Default apps with calendar app
</details>

**The content of config/config.php:**
<details>
Default, no changes
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE11 and Microsoft Edge

**Operating system:**
Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
unlink(/cloud/themes/example/core/templates/lostpassword/email.php): No such file or directory at /cloud/apps/templateeditor/lib/mailtemplate.php#127 
```
</details>

### PR DESCRIPTION
**Pull request by MorrisJobke**
- fixes nextcloud/server#503

@Dennis1993 could you test this?

cc @nickvergessen @rullzer @schiessle 

@karlitschek I would like to backport this to avoid the error message.

### CODE REVIEW

**Comment by karlitschek** [comment]
please backport 👍

File: lib/mailtemplate.php [hunk 1]
```diff
@@ -124,8 +124,10 @@ public function reset(){
 					if (rename($absolutePath.'.bak', $absolutePath)) {
 						return true;
 					}
-				} else if (unlink($absolutePath)) {
-					return true;
+				} else if(file_exists($absolutePath)) {
+					if (unlink($absolutePath)) {
```
Comment (nickvergessen) [inline lib/mailtemplate.php:128]: use `&&` instead of nesting?

**Comment by nickvergessen** [comment]
:+1:

File: lib/mailtemplate.php (hunk 1 above)
Comment (MorrisJobke) [reply lib/mailtemplate.php:128]: I was against this, because then the logic makes more sense. Just to have it grouped logically - "only unlink if the file_exists" and "when the unlink succeeds then return success". 

Sure from an logical point this can be combined but just makes things harder to understand in the future.

**Comment by MorrisJobke** [comment]
I will merge this - see explanation above for your comment ;)
